### ISSUE TITLE
为什么无论传什么参数，验证结果都是true呢

### ISSUE THREAD

**Issue by caiweiming** [shahradelahi/react-geetest#1]
我用的是next.js，新建了一个验证文件
/api/geetest/verify.ts

`
import { NextApiRequest, NextApiResponse } from 'next';
import { validateCaptcha, generateSignToken } from 'react-geetest-v4';

const CAPTCHA_ID = '';
const CAPTCHA_KEY = '';

export default async function handler(req: NextApiRequest, res: NextApiResponse) {
  const { captcha_output, gen_time, lot_number, pass_token } = req.body;
  if (!captcha_output || !gen_time || !lot_number || !pass_token) {
    return res.status(400).json({ error: '缺少参数' });
  }

  const validate = await validateCaptcha({
    captcha_id: CAPTCHA_ID,
    sign_token: generateSignToken(lot_number, CAPTCHA_KEY),
    lot_number,
    captcha_output,
    pass_token,
    gen_time,
  });

  return res.status(200).json({ ok: validate });
}
`
当我随便提交一些参数到这个请求时，返回的结果都是{ok:true}

**Comment by caiweiming** [comment]
我用的是yarn add react-geetest-v4 命令来添加的

**Comment by shahradelahi** [comment]
Hi  @caiweiming,

This action is happening on [this line.](https://github.com/shahradelahi/react-geetest/blob/aadb852e7f80b2a6362c66c10e8500acccbf155e/src/Server.ts#L23)

This is because of GeeTest is not configured correctly and GeeTest Validator server is responding with an error status.

A possible way to fix it, make sure you are passing the valid `ID` and `KEY`.

**Comment by shahradelahi** [comment]
Hi @caiweiming,

Please check the new release, it should fix this issue.

```bash
yarn add react-geetest-v4@1.1.0
```

On this release, you can access the exact response from the server.

```js
import { validateCaptcha, generateSignToken } from 'react-geetest-v4';

const CAPTCHA_ID = '';
const CAPTCHA_KEY = '';

export default async function handler(req: NextApiRequest, res: NextApiResponse) {

    // ... 

    const result = await validateCaptcha({
      captcha_id: CAPTCHA_ID,
      lot_number,
      captcha_output,
      pass_token,
      gen_time,
      sign_token: generateSignToken(lot_number, CAPTCHA_KEY)
   })

   
   return res.status(200).json({ ok: result.result === 'success' })

}
```
