### ISSUE TITLE
Reset the captcha validation or clear captcha when some API Server if its error

### ISSUE THREAD

**Issue by rahXephonz** [shahradelahi/react-geetest#4]
basically i have logic for signin in here

```tsx
signInWithOTP(
        {...jsonPayload, ...geetestData},
        {onError: () => {/*do in here*/}}
)
```

how to reseting the captcha from start if some error happen?

**Comment by shahradelahi** [comment]
```tsx
  const captchaRef = React.useRef<GeeTestRef | null>(null)
  const handleLogin = () => {
    try {
      // do login
    } catch (e) {
      // handle error
    } finally {
      // reset captcha
      captchaRef.current?.reset()
    }
  }
```

**Comment by rahXephonz** [comment]
Thanks @shahradelahi !!! Awesome :) 👍🏿

**Comment by rahXephonz** [comment]
Hello @shahradelahi did you know how to change captcha challenge from slide into another? Thanks

**Comment by shahradelahi** [comment]
Hello @rahXephonz,
To change the Geetest security strategy, refer to their console/dashboard and apply the changes on the `Customization > Security strategy` page.
If you want more product support, you can contact the Geetest support team.
